#!/usr/bin/env python
# -*- coding: utf-8 -*-


sectores = {
    'ABERTIS_INFR': 'Servicios',
    'ACCIONA': 'Construccion',
    'ACERINOX': 'Construccion',
    'ACS_CONST': 'Construccion',
    'AENA': 'Servicios',
    'AMADEUS': 'Tecnologia',
    'ARCEL.MITTAL.': 'Construccion',
    'BANKIA': 'Bancos',
    'B.POPULAR': 'Bancos',
    'B.SABADELL': 'Bancos',
    'SANTANDER': 'Bancos',
    'BANKINTER': 'Bancos',
    'BBVA': 'Bancos',
    'CAIXABANK': 'Bancos',
    'DIA': 'Servicios',
    'ENAGAS': 'Energia',
    'ENDESA': 'Energia',
    'FCC': 'Construccion',
    'FERROVIAL': 'Construccion',
    'GAMESA': 'Construccion',
    'GAS_NATURAL': 'Energia',
    'GRIFOLS': 'Bienes',
    'INT.AIRL.GRP': 'Servicios',
    'IBERDROLA': 'Energia',
    'INDITEX':'Bienes',
    'INDRA':'Teconologia',
    'MAPFRE':'Bancos',
    'MEDIASET_ESP':'Servicios',
    'MERLIN_PROP': 'Bancos',
    'OBR.H.LAIN': 'Construccion',
    'RED_ELE.CORP': 'Energia',
    'REPSOL':'Energia',
    'SACYR':'Construccion',
    'TEC.REUNIDAS':'Teconologia',
    'TELEFONICA':'Tecnologia',
}
